name = "chatterbox-tts"
description = "Chatterbox TTS Generation Handler"
repository = "https://github.com/yourusername/runpod_chatterbox"
docker_image_name = "chatterbox-tts"
docker_image_tag = "latest"

[env]
NEXT_PUBLIC_VC_CB_ENDPOINT_ID = "your-chatterbox-voice-clone-endpoint-id-here"
NEXT_PUBLIC_TTS_CB_ENDPOINT_ID = "your-chatterbox-tts-endpoint-id-here"
NEXT_PUBLIC_VC_Higgs_ENDPOINT_ID = "your-higgs-voice-clone-endpoint-id-here"
NEXT_PUBLIC_TTS_Higgs_ENDPOINT_ID = "your-higgs-tts-endpoint-id-here"

[build]
dockerfile = "Dockerfile.tts"
context = "."

[deploy]
gpu_type = "RTX 4090"
container_disk_in_gb = 50
volume_in_gb = 100
ports = "8000/http"
envs = [
    "NEXT_PUBLIC_VC_CB_ENDPOINT_ID",
"NEXT_PUBLIC_TTS_CB_ENDPOINT_ID",
"NEXT_PUBLIC_VC_Higgs_ENDPOINT_ID",
"NEXT_PUBLIC_TTS_Higgs_ENDPOINT_ID"
] 