name = "higgs-tts"
description = "Higgs Audio TTS Generation Handler"
repository = "https://github.com/chrijaque/runpod_chatterbox"
docker_image_name = "higgs-tts"
docker_image_tag = "latest"

[env]
RUNPOD_API_KEY = "{{ RUNPOD_API_KEY }}"
FIREBASE_STORAGE_BUCKET = "{{ FIREBASE_STORAGE_BUCKET }}"

[build]
dockerfile = "dockerfiles/higgs/Dockerfile.tts"
context = "."

[deploy]
gpu_type = "RTX 4090"
container_disk_in_gb = 50
volume_in_gb = 100
ports = "8000/http"
envs = [
    "RUNPOD_API_KEY",
    "FIREBASE_STORAGE_BUCKET"
]
volumes = [
    "dtabrd8bbd:/runpod-volume"
] 